services:
  nginx:
    image: nginx:alpine
    container_name: nimbus-nginx
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - nimbus_internal_network

  frontend:
    build:
      context: .
      dockerfile: infrastructure/docker/frontend/Dockerfile
    container_name: nimbus-frontend
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nimbus_nginx_generated:/etc/nginx/generated
    expose:
      - "5173"
    restart: unless-stopped
    networks:
      - nimbus_internal_network

  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/backend/Dockerfile
    container_name: nimbus-backend
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_TOKEN_ENCRYPTION_KEY: ${GITHUB_TOKEN_ENCRYPTION_KEY}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}

      NIMBUS_BASE_URL: ${NIMBUS_BASE_URL}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

      # Nimbus needs access to the host Docker Engine.
      - /var/run/docker.sock:/var/run/docker.sock

      # Nginx configuration files generated by the backend.
      - nimbus_nginx_generated:/shared/nginx/generated
      
      # Deployment logs
      - nimbus_logs:/var/lib/nimbus/logs
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nimbus_internal_network

  postgres:
    image: postgres:18-alpine
    container_name: nimbus-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - nimbus_internal_network

volumes:
  postgres_data:
  nimbus_nginx_generated:
  frontend_node_modules:
  backend_node_modules:
  nimbus_logs:

networks:
  nimbus_internal_network:
    driver: bridge